### ISSUE TITLE
Suicide Barbie Source-Code

### ISSUE THREAD

**Issue by JayFoxRox** [theblacklotus/blog#3]
Hey, any chance that you guys could upload the source-code and project files for Suicide Barbie?
I'd consider remixing it and porting it to other platforms.

If you aren't willing to share the code (should be GPLv2 or later compatible, because some statically linked platforms require this) then I'd be grateful for some articles. I remember some post on ps2dev about how you experimented with implementations for the bloom-pass. I believe such posts have disappeared since then.

Suicide Barbie is still one of my favorite demos overall.

**Comment by JayFoxRox** [comment]
I found the old ps2dev thread: [Suicide Barbie demo [Final version]](http://lukasz.dk/mirror/forums.ps2dev.org/viewtopic6519.html?t=8796).

Unfortunately not too technical and no source-code either.

**Comment by erique** [comment]
Hi @JayFoxRox 
I started looking into what it would take to do this a few years ago, after discussing it with ReJ a few times, and as such it's been a low-intensity effort mostly on my plate.

It's basically an old Perforce repo, with source code / development environment very much tied to 32bit Win XP and Visual Studio 2005 plugin hacks.
I would say it's probably realistic to "port" the PSP runtime setup to something more modern, but the tooling pipeline and the DX9 runtime backend would probably have to be left behind.

As it stands right now it's just a messy heap of tooling and runtime source code, and no mechanism of building it..  But seeing as there is actual interest from the community I guess we can bump it up in the priority queue; no promises tho ;-)

**Comment by JayFoxRox** [comment]
Sounds good!

> I would say it's probably realistic to "port" the PSP runtime setup to something more modern

I'm actually interested in running (and potentially remixing) this bare-metal (with our custom GPU drivers) on original Xbox (Pentium 3, 733MHz, nvidia GeForce 3-ish, 64MiB shared RAM).
I have also worked with the PSP GE and PSP GU libs in the past, so I assume this is feasible.

> but the tooling pipeline and the DX9 runtime backend would probably have to be left behind.

I expect a lot of work to go into rewriting things (aspect ratio, algorithm changes, optimizing resources for original Xbox, ..) anyway. So if it's not working out-of-the-box that's fine with me.

Even if I don't end up porting it, I'd still be very interested to take a look at this piece of demoscene history.

**Comment by erique** [comment]
@JayFoxRox took a while but here it is : https://github.com/theblacklotus/suicide-barbie

**Comment by JayFoxRox** [comment]
Holy shit! This is amazing. Thank you so much!

A lot of what is said in the README is also a very good guideline for cross-platform and embedded development.
MIT and CC licenses are excellent choices for this.
I really like what you released here.

I'll try looking at the actual files and compiling it later.

I'm also closing this issue, because the code is public now. A blog post pointing at it would be nice, but that's up to you guys.
